// src/components/ui/icons.tsx --> 

import {
  Loader2,
  LucideProps,
  User,
  Mail,
  Lock,
  Building,
  Search, 
  Calendar,
  FileText,
  Package,
  AlertTriangle,
  Settings,
  Bell,
  XCircle,
  CheckCircle,
  Plus,
  TrendingUp,
  TrendingDown,
  Minus,
  LayoutDashboard,
  Ship,
  Truck,
  Plug,
  Brain,
  Timer,
  DollarSign,
} from 'lucide-react';
import { FaGoogle, FaFacebook, FaLinkedin, FaMicrosoft } from 'react-icons/fa';

export const Icons = {
  spinner: Loader2,
  user: User,
  mail: Mail,
  lock: Lock,
  building: Building,
  search: Search,
  package: Package,    // Assuming you want to use the "Package" icon for shipments
  calendar: Calendar,
  fileText: FileText,
  alertTriangle: AlertTriangle,
  settings: Settings,
  google: FaGoogle,
  microsoft: FaMicrosoft,
  bell: Bell,
  xCircle : XCircle,
  checkCircle : CheckCircle,
  plus: Plus,
  trendingUp : TrendingUp,
  trendingDown : TrendingDown,
  minus : Minus,
  layoutDashboard : LayoutDashboard,
  truck : Truck,
  plug : Plug,
  ship: Ship,
  brain: Brain,
  timer: Timer,
  dollarSign: DollarSign,
} as const;